directories:
    type:     rest
    resource: Symcloud\Bundle\StorageBundle\Controller\DirectoryController

files:
    type:     rest
    resource: Symcloud\Bundle\StorageBundle\Controller\FileController

blob_files:
    type:     rest
    resource: Symcloud\Bundle\StorageBundle\Controller\BlobController

objects:
    type:     rest
    resource: Symcloud\Bundle\StorageBundle\Controller\ObjectController
    resource: Symcloud\Bundle\StorageBundle\Controller\BlobController

references:
    type:     rest
    resource: Symcloud\Bundle\StorageBundle\Controller\ReferenceController
